// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNcOEKY_rjKIWN-bY-sYvmm-HnfG-aaz0',
    appId: '1:793572673225:web:806ef247ae60c44c772f18',
    messagingSenderId: '793572673225',
    projectId: 'cash-management-92d3d',
    authDomain: 'cash-management-92d3d.firebaseapp.com',
    storageBucket: 'cash-management-92d3d.appspot.com',
    measurementId: 'G-YVD8HGBPWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0EWnnekLRg0D3p5NI3rGPE6ntH4-ASE',
    appId: '1:793572673225:android:accd3ea844a2f7c2772f18',
    messagingSenderId: '793572673225',
    projectId: 'cash-management-92d3d',
    storageBucket: 'cash-management-92d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWOXP5DxmpYbt0sCVXzv5rmkbjggu1wPE',
    appId: '1:793572673225:ios:cf2fcfd93e1cfaaa772f18',
    messagingSenderId: '793572673225',
    projectId: 'cash-management-92d3d',
    storageBucket: 'cash-management-92d3d.appspot.com',
    iosClientId: '793572673225-9gsa0uat4deu0qos5fdlcks4sh07ev3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashManagementProject',
  );
}
